"""Standardized, machine-readable reason codes.

Every rejected or flagged observation carries exactly one of these codes
(rejection) or one-or-more of these codes (flags) rather than a free-text
message, so a dashboard or downstream service can group/count on them
without parsing strings. See docs/data_quality.md for what triggers each.
"""

from __future__ import annotations

# --- Rejection reasons (record cannot safely enter the index pipeline) ----

MISSING_OBSERVATION_ID = "MISSING_OBSERVATION_ID"
MISSING_AIRLINE = "MISSING_AIRLINE"
MISSING_ORIGIN = "MISSING_ORIGIN"
MISSING_DESTINATION = "MISSING_DESTINATION"
INVALID_AIRPORT_CODE = "INVALID_AIRPORT_CODE"
SAME_ORIGIN_DESTINATION = "SAME_ORIGIN_DESTINATION"
INVALID_FLIGHT_DATE = "INVALID_FLIGHT_DATE"
INVALID_BOOKING_DATE = "INVALID_BOOKING_DATE"
NEGATIVE_BOOKING_HORIZON = "NEGATIVE_BOOKING_HORIZON"
MISSING_CURRENCY = "MISSING_CURRENCY"
NON_INR_CURRENCY = "NON_INR_CURRENCY"
NON_POSITIVE_FARE = "NON_POSITIVE_FARE"
EXACT_DUPLICATE = "EXACT_DUPLICATE"
INVALID_SCHEMA = "INVALID_SCHEMA"

REJECTION_REASONS = (
    MISSING_OBSERVATION_ID,
    MISSING_AIRLINE,
    MISSING_ORIGIN,
    MISSING_DESTINATION,
    INVALID_AIRPORT_CODE,
    SAME_ORIGIN_DESTINATION,
    INVALID_FLIGHT_DATE,
    INVALID_BOOKING_DATE,
    NEGATIVE_BOOKING_HORIZON,
    MISSING_CURRENCY,
    NON_INR_CURRENCY,
    NON_POSITIVE_FARE,
    EXACT_DUPLICATE,
    INVALID_SCHEMA,
)

# --- Flag reasons (structurally valid, but deserves attention) ------------

SUSPICIOUS_FARE = "SUSPICIOUS_FARE"
UNMAPPED_LOCATION = "UNMAPPED_LOCATION"
UNKNOWN_AIRLINE = "UNKNOWN_AIRLINE"
MISSING_OPTIONAL_FIELD = "MISSING_OPTIONAL_FIELD"
STALE_OBSERVATION = "STALE_OBSERVATION"
UNUSUAL_BOOKING_HORIZON = "UNUSUAL_BOOKING_HORIZON"
POTENTIAL_DUPLICATE = "POTENTIAL_DUPLICATE"

FLAG_REASONS = (
    SUSPICIOUS_FARE,
    UNMAPPED_LOCATION,
    UNKNOWN_AIRLINE,
    MISSING_OPTIONAL_FIELD,
    STALE_OBSERVATION,
    UNUSUAL_BOOKING_HORIZON,
    POTENTIAL_DUPLICATE,
)

# --- Observation status -----------------------------------------------------

STATUS_VALID = "VALID"
STATUS_FLAGGED = "FLAGGED"
STATUS_REJECTED = "REJECTED"

# --- Scraper/source health status ------------------------------------------

HEALTH_HEALTHY = "HEALTHY"
HEALTH_DEGRADED = "DEGRADED"
HEALTH_FAILED = "FAILED"
HEALTH_UNKNOWN = "UNKNOWN"
